name: Thesis CI

on:
  push:
    branches: [ main ]
    paths:
      - "thesis/**"
      - ".github/workflows/thesis.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "thesis/**"
      - ".github/workflows/thesis.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build PDF and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: thesis
          root_file: thesis.tex
          texlive_version: latest
          extra_system_packages: coreutils icu inkscape

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: |
            thesis/README.md
            thesis/thesis.pdf

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/jdujava/cuni-thesis-validator
    steps:
      - name: Get PDF artifact
        uses: actions/download-artifact@v4

      - name: Verify PDF with VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'

  deploy:
    name: Deploy latest PDF and landing page to gh-pages
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4

      - name: Commit and push to gh-pages
        run: |
          cd Thesis
          mv README.md index.md
          cat > _config.yml <<'EOF'
          title: Statistical Post-processing of Multidimensional Climate Data
          description: Diploma thesis by Bc. Jan Kovacovsky
          EOF
          git init -b temp
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[CI] Update latest thesis PDF"
          git push --force origin temp:gh-pages
